# Generated by Django 4.2.5 on 2023-10-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
